### ISSUE TITLE
Discuss evaluation of likelihood under coalescent model

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/what-is-an-arg-paper#34] opened 2022-01-15 15:10 UTC
Computing the likelihood of a given ARG under the coalescent with recombination model is non trivial.

If we are given a standard Griffiths-like ARG as input (nodes annotated with breakpoints) then I think computation amounts to running ``simplify`` on it. Basically, we visit each node in time order and then compute the overall rate of recombination. This requires knowing the amount of extant ancestral material at the time of each node, which means keeping track of all the segments of ancestral material and how they coalesce === simplify.

Things are simpler if we have an edge annotated ARG (right @JereKoskela ?)

We cannot evaluate the likelihood of a node-minimal edge annotated ARG though, because there is insufficient information available.

I think this is a good thing to explain, because it's a an application where seemingly you really do need a "real" ARG, but it turns out that you have to do a lot of work to propagate the information you need through the graph.

**Comment by jeromekelleher** [comment] 2022-01-15 15:17
I guess the alternative to doing this is to evaluate the likelihood of the input ARG under the Big ARG stochastic process, which does *not* track marginal coalescences. It therefore contains lots of non genetic ancestor nodes, because it has no way of stopping until it gets to the GMRCA (which is exponentially long ago, but happens with probability 1).

Of course this would be completely useless as Big ARG space is absurdly large. The price we pay for coming down from Big ARG space to the Little ARG is that we have to track ancestral material and marginal coalescences, in some way.

Am I getting this right @jerekoskela? The Big ARG likelihood should be easy to write down, right?

**Comment by JereKoskela** [comment] 2022-01-15 17:28
I don't think node-annotated vs edge annotated makes a big difference, conceptually. The key is that you have to annotate with enough information to work out the number of extant lineages and the amount of extant material at each time in the ARG. That is probably possible if you just annotate nodes with, but will be very labour-intensive. Essentially, you would have to build a record the segments along each edge during runtime. Edge-annotating alleviates that workload, but doesn't completely free you of the need to annotate nodes with breakpoints as well, as discussed over in the msprime repo.

Yes, the big ARG likelihood is really easy in comparison. The number of "extant links" is always equal to the product of the length of the segment and the number of extant lineages, so tracking just the number of lineages is enough.

**Comment by jeromekelleher** [comment] 2022-01-16 10:45
Great, that's what I was thinking. These are not widely understood properties, I think, and good to explain. The computational properties are important, and determine what is feasible in terms of methods that statistically sample from models like the coalescent. 

I think the distinction computation-wise, is that you essentially have to produce an edge annotated ARG from the node annotated one in order to calculate this value (but modulo the issues we're working out in the msprime repo, as you say).

**Comment by jeromekelleher** [comment] 2022-03-10 15:45
@JereKoskela reading [this preprint](https://www.biorxiv.org/content/10.1101/2022.02.08.479599v2) I see that evaluating likelihoods is perhaps coming back into fashion, so we should have a good answer about what level of detail we need in an ARG inorder to do it.

We know that you can't do this with a fully simplified GARG. Maybe there's a short section on this after the "ARGs and SPRs" section discussing this, and referring back to Fig 5 for examples?

Of course the example in Fig 5 might break things a bit since it violates coalescent assumptions.

Thoughts?

**Comment by hyanwong** [comment] 2022-03-10 15:50
Can we do it with Fig 5b (removing diamonds). I'm not sure we can, because in this case we also remove pass through nodes like H, so that the 2 parents of a recombinant are at different times.

**Comment by jeromekelleher** [comment] 2022-03-10 17:24
I think this is important to discuss because it's the only application I can think of in which inferring a "true" ARG really matters. All the rest are just looking at the trees marginally AFAIK. So could be part of a section "downstream applications" or something?

**Comment by JereKoskela** [comment] 2022-03-10 19:20
Sounds good to me. I'll put together a draft paragraph and we can see how it reads. It will essentially be a slightly more verbose retelling of my usual mantra: you have to know the number of extant links and lineages at all times. I think that effectively requires Fig 5a.

Speaking of Fig 5a, I spotted a potential source of confusion. @hyanwong, am I right in reading nodes P, Q, N, and O as parents of recombinants? If so, then it looks like there are 4 lineages in the time interval from M to N, when I think there are actually 2; the material going into P and Q is all still part of the same lineage until the time of P and Q, right? And similarly for K to N and O. If that's right, then I guess this is a downside of drawing the ARG like a traditional graph, and avoiding a single vertical lineage which suddenly bifurcates into 2 horizontally. I'm not sure which approach is better, but we should explain whichever way we end up using.

**Comment by hyanwong** [comment] 2022-03-10 19:53
> Speaking of Fig 5a, I spotted a potential source of confusion. @hyanwong, am I right in reading nodes P, Q, N, and O as parents of recombinants? 

Yes, that's right.

> If so, then it looks like there are 4 lineages in the time interval from M to N, when I think there are actually 2; 

Ah, yes. I see what you mean. That's a really good point. The problem here is that we are stating that the recombination "happens" when we see the parents, but we don't have the gamete available immediately.

I'm not sure this is resolved by simply drawing the lines like a "T", as Jerome points out that the jointing point of the T shouldn't be thought of as a node in the graph (it's simply a pictographic convention), so we would still have 2 edges below the parent.

The other option is to create a node for the gamete, either in the generation below the parents, or (more of a hack) half a generation below the parent. I know Jerome didn't like either of these options.

**Comment by hyanwong** [comment] 2022-03-10 19:58
> I'm not sure this is resolved by simply drawing the lines like a "T", as Jerome points out that the joining point of the T shouldn't be thought of as a node in the graph (it's simply a pictographic convention), so we would still have 2 edges below the parent, all the way back to the genome in which the recombination becomes visible to us.

The more I think about this, the trickier it gets. The problem with drawing a "T" is that you then (suddenly!) have imposed a distinction between 2 types of nodes: "parent of recombination" (which come in pairs and are joined with a T) and "other". One of our main arguments for the gARG representation is that it doesn't need to distinguish between nodes of different types.

**Comment by JereKoskela** [comment] 2022-03-10 20:04
I don't think this needs to have anything to do with the data structure. From the point of the likelihood function, there is no problem having two separate edges from the recombinant child rootwards as long as that's documented. I would expect the same is true of any other potential application. The issue is just how to make the visualisation as intuitive for what we mean as possible.

**Comment by hyanwong** [comment] 2022-03-10 20:06
But don't you require the ability to identify the parent nodes of a recombinant, and flag up that they are different, for the purposes of the likelihood calculation?

**Comment by JereKoskela** [comment] 2022-03-10 20:11
Sure. But not any more so than is already encoded into the edge list: a common ancestor node has in-degree > 1, and a recombinant has out-degree > 1. Under the CwR, the two are mutually exclusive. You find the parents by checking the parents of those edges in which the recombinant appears as a child.

**Comment by hyanwong** [comment] 2022-03-10 20:13
So we need to "know" that the edges above a recombinant follow the same lineage, until such a point as they jointly hit the two parents. With the convention that a recombinant must have two parents at a single time, which flags the time at which the recombination event happened.

Here, a parent can also be a recombinant itself, right? Even in the CwR.

**Comment by hyanwong** [comment] 2022-03-10 20:23
> Sure. But not any more so than is already encoded into the edge list: a common ancestor node has in-degree > 1, and a recombinant has out-degree > 1.

And in a msprime "full ARG" tree sequence, we can find such nodes by counting the number of edges in which they are children, without regard for the genomic location. This should (always) be 1 or 2, regardless of the length of the genome. But the edges need not be contiguous, if this is in a non-ancestral region. It all seems a bit more fragile than I had hoped.

> The issue is just how to make the visualisation as intuitive for what we mean as possible.

It isn't that intuitive to me that you have what looks like a point at which 2 lines join, but they don't actually join there (there is no node). Or to put it another way: from the point of view of the graph structure, they are separate edges, but from the point of view of lineage counting, they are one edge.

Moreover, you couldn't adopt the "T" shaped convention once you simplify the tree sequence at all, as then you may end up removing one or other of the parents, and you don't know in which parts of the graph the lines should be counted as shared. So we'd need to switch back to a "V" shaped version in e.g. Figs 5 b, c, and d.

**Comment by JereKoskela** [comment] 2022-03-10 21:24
> It isn't that intuitive to me that you have what looks like a point at which 2 lines join (the top of the T), but they don't actually join there (there is no node). Or to put it another way: from the point of view of the graph structure, they are separate edges, but from the point of view of lineage counting, they are one edge.

Fair enough. It is to me, but then I've been drawing ARGs that way for 10 years without really thinking about it, so my preference should definitely not be the deciding factor.

> Moreover, you couldn't adopt the "T" shaped convention once you simplify the tree sequence at all, as then you may end up removing one or other of the parents, and you don't know in which parts of the graph the lines should be counted as shared. So we'd need to switch back to a "V" shaped version in e.g. Figs 5 b, c, and d.

True, the T makes no sense as soon as you simplify enough to lose the number of extant lineages anyway.

> These complexities are avoided if we actually introduce the genome-as-a-gamete node, just below the parents of a recombinant. But that also seems messy.

I'd prefer to avoid extraneous nodes if we can. At a minimum, we'd need to explain that it's not needed but makes some bookkeeping easier. That doesn't seem easier than explaining either the T, or the absence of the T.

**Comment by jeromekelleher** [comment] 2022-03-11 09:38
Hmmm, I'll have to think about this. 

But, I think Fig 5 is probably not the right basis for explaining this since it is a WF simulation and (by design) violates the CwR assumptions. We perhaps don't need to get into the details of explaining this with an example, and can maybe talk about it from a higher level. Which is, we are basically recreating the state of Hudson's algorithm (Fig 1) by visiting each node in the graph in time order?

**Comment by hyanwong** [comment] 2022-03-11 09:42
Yes, I think explaining this might overload Fig 5. It may be worth pointing out somewhere that the 2 edges of a recombinant can "share" the same lineage for a period of time (perhaps only 1 generation). To me the natural place to explain this is in Fig 3.

**Comment by jeromekelleher** [comment] 2022-03-11 09:54
> It may be worth pointing out somewhere that the 2 edges of a recombinant can "share" the same lineage for a period of time (perhaps only 1 generation). 

I think that's a function of the assumed generative model - the lineages certainly weren't shared when Fig 5 was simulated. Under a true CwR output I expect this issue goes away.

**Comment by hyanwong** [comment] 2022-03-11 10:39
Another thought I had on this. Actually one of the main points of fig 5 is that we can get rid of nodes, but by so doing, we often lose information about which edges actually share a lineage. For example, when moving from 5a to 5b we make it seem as if the lineages from D->M and D->S are completely independent, whereas we know that they are shared at least to node I.

So the issue that @JereKoskela raised ties in with a more general point about knowledge of lineages vs simplification.

**Comment by hyanwong** [comment] 2022-03-11 14:35
Note that this issue with the "V" shaped recombination edges is even clearer in the Wiuf & Hein ARG in Fig 4, now that I re-examine it.

**Comment by JereKoskela** [comment] 2022-03-11 14:46
Lineage knowledge vs simplification seems like a good way to phrase this. I could try and put an explanation into the likelihood evaluation paragraph (and refer to Fig 4 for an example), because that will bring up the concept of knowing the number of lineages explicitly.

**Closed** 2023-07-18 08:56 UTC
